In [1]:
import pandas as pd 

df = pd.read_csv("../data/raw/lat_long_kota_kab.csv")

df.head()

   Unnamed: 0    id  foreign                     name      lat      long
0           0  1101       11       KABUPATEN SIMEULUE  2.46158  96.38105
1           1  1102       11   KABUPATEN ACEH SINGKIL  2.28411  97.79769
2           2  1103       11   KABUPATEN ACEH SELATAN  3.26142  97.17933
3           3  1104       11  KABUPATEN ACEH TENGGARA  3.48673  97.81081
4           4  1105       11     KABUPATEN ACEH TIMUR  4.94789  97.77651

In [2]:
location_df = df[
    [
        "name",
        "lat",
        "long"
    ]
].copy()

location_df.columns = [
    "kabupaten_kota",
    "latitude",
    "longitude"
]

location_df.head()

            kabupaten_kota  latitude  longitude
0       KABUPATEN SIMEULUE   2.46158   96.38105
1   KABUPATEN ACEH SINGKIL   2.28411   97.79769
2   KABUPATEN ACEH SELATAN   3.26142   97.17933
3  KABUPATEN ACEH TENGGARA   3.48673   97.81081
4     KABUPATEN ACEH TIMUR   4.94789   97.77651

In [7]:
# hapus kolom index lama
df = df.drop(columns=["Unnamed: 0"])

# rename kolom
df = df.rename(columns={
    "name": "kabupaten_kota",
    "lat": "latitude",
    "long": "longitude"
})

# rapikan nama wilayah
df["kabupaten_kota"] = (
    df["kabupaten_kota"]
    .str.title()
)

df.head()

     id  foreign           kabupaten_kota  latitude  longitude
0  1101       11       Kabupaten Simeulue   2.46158   96.38105
1  1102       11   Kabupaten Aceh Singkil   2.28411   97.79769
2  1103       11   Kabupaten Aceh Selatan   3.26142   97.17933
3  1104       11  Kabupaten Aceh Tenggara   3.48673   97.81081
4  1105       11     Kabupaten Aceh Timur   4.94789   97.77651

In [8]:
location_df = df[
    [
        "kabupaten_kota",
        "latitude",
        "longitude"
    ]
]

location_df.head()

            kabupaten_kota  latitude  longitude
0       Kabupaten Simeulue   2.46158   96.38105
1   Kabupaten Aceh Singkil   2.28411   97.79769
2   Kabupaten Aceh Selatan   3.26142   97.17933
3  Kabupaten Aceh Tenggara   3.48673   97.81081
4     Kabupaten Aceh Timur   4.94789   97.77651

In [9]:
location_df.to_csv(
    "../data/clean/lat_long_kab_kota_clean.csv",
    index=False
)